// <auto-generated />
using IIoT.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace IIoT.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(IIoTDbContext))]
    [Migration("20260622093000_AddDeviceClientVersionNetworkAddresses")]
    partial class AddDeviceClientVersionNetworkAddresses
    {
    }
}
